---
title: "Trabalho 1 - Aprendizado de Máquina"
output: html_notebook
---

```{r}
library(data.tree)

computeEntropy <- function(data, attIndex=NULL, classIndex) {
    #classes no problema 
    classes <- unique(data[,classIndex])
    
    #se attIndex nao for informado, calcula a entropia (Info(D)) para o conjunto de dados inteiro
    if (is.null(attIndex)) {
        #a priori entropy
        
        entropy<-0
        for (ii in 1:length(classes)){
            temp<- length(which(data[[classIndex]] == classes[ii]))
            prob <- temp/dim(data)[1]
            entropy <- entropy + (-(prob*log2(prob)))
        }
    } else{
        #caso contrário, calcula a entropia restrita a um subconjunto de dados 
        # (após particao por valor 'v' do atributo 'A')
        if(is.numeric(data[, attIndex]))
        {
          values <- 2
          entropy <- 0

          temp1 <- length(which(data[,attIndex] > mean(data[,attIndex])))
          prob1 <- temp1/dim(data)[1]
          data.subset <- data[which(data[,attIndex] > mean(data[,attIndex])),]
          soma <- 0
          for(ii in 1:length(classes)){
            temp <- length(which(data.subset[,classIndex] == classes[ii]))
            if(temp > 0){
              prob <- temp/dim(data.subset)[1]
              soma <- soma+(-(prob*log2(prob)))
            }else{
              soma <- soma+0
            }
          }
          entropy <- entropy + (prob1*soma)
          
          temp1 <- length(which(data[,attIndex] <= mean(data[,attIndex])))
          prob1 <- temp1/dim(data)[1]
          data.subset <- data[which(data[,attIndex] <= mean(data[,attIndex])),]
          soma <- 0
          for(ii in 1:length(classes)){
            temp <- length(which(data.subset[,classIndex] == classes[ii]))
            if(temp > 0){
              prob <- temp/dim(data.subset)[1]
              soma <- soma+(-(prob*log2(prob)))
            }else{
              soma <- soma+0
            }
          }
          entropy <- entropy + (prob1*soma)
        }
        else{
          values<- unique(data[,attIndex])
          entropy<-0
          for (jj in 1:length(values)) {
              temp1 <- length(which(data[,attIndex] ==values[jj])) 
              prob1 <- temp1/dim(data)[1]
              data.subset <- data[which(data[,attIndex] ==values[jj]),]
              soma<-0
              for (ii in 1:length(classes)){
                  temp<- length(which(data.subset[,classIndex]==classes[ii]))
                  if(temp > 0){
                      prob <- temp/dim(data.subset)[1]
                      soma <- soma+(-(prob*log2(prob)))
                  }else{
                      soma <- soma+0
                  }
              }
              entropy <- entropy + (prob1*soma)
          }
        }
    }
  entropy
    }  
```

```{r}
randomAttr <- function(data){
  colId <- sample(1:ncol(data), round(sqrt(ncol(data))), replace=FALSE)
  #print(colId)
  return(colId)
}
```

```{r}
computeTree <- function(tree, data, indexClass){
  randomAtt <- randomAttr(data[-indexClass])
  #print(randomAtt)
  entropyClass <- computeEntropy(data, NULL, indexClass)
  entropies <- numeric(ncol(data)-1)
  for(i in 1:length(randomAtt)){
    entropies[randomAtt[i]] <- entropyClass - computeEntropy(data, attIndex = randomAtt[i], indexClass)
  }
  maxGain <- which.max(entropies)
  #print(maxGain)
  if(!is.numeric(data[[maxGain]])){
    test <- unique(data[maxGain])
    entropies <- NULL
    entropies <- numeric(nrow(test))
  }
  
  subData <- list()
  if(is.numeric(data[[maxGain]])){
    if(length(unique(data[[maxGain]])) == 1){
      #print(unique(data[[maxGain]]))
      #print("teste1")
      #print(names(which.max(table(data[,indexClass]))))
      #print(data)
      
      
      if(length(unique(table(data[,indexClass]))) == 1){
        #print(unique(data[,indexClass])[sample(1:2, 1)])
        #print(data)
        tree <- tree$AddChild(unique(data[,indexClass])[sample(1:2, 1)])
      } else {
      tree <- tree$AddChild(names(which.max(table(data[,indexClass]))))
      }
      
    } else {
      #print("teste2")
    tree  <- tree$AddChild(colnames(data)[maxGain])
    for(i in 1:2){
      if(i == 1){
        child <- tree$AddChild(paste("<=", mean(data[,maxGain])))
        subData[[i]] <- data[which(data[,maxGain] <= mean(data[,maxGain])),]
      } 
      else { 
        child <- tree$AddChild(paste(">", mean(data[,maxGain]))) 
        subData[[i]] <- data[which(data[,maxGain] > mean(data[,maxGain])),]

        }
    if(length(unique(subData[[i]][,indexClass])) > 1){
      child <- computeTree(child, subData[[i]], indexClass)
    } 
    else if(length(unique(subData[[i]][,indexClass]))){

      #print(length(unique(subData[[i]][,indexClass])))
      child$AddChild(unique(subData[[i]][,indexClass]))
    }
    }
    }
  }
  else{
    tree  <- tree$AddChild(colnames(data)[maxGain])
    for(i in 1:(nrow(test))){
      child <- tree$AddChild(test[[1]][i])
      subData[[i]] <- data[which(data[[maxGain]]==test[[1]][i]),]
      if(length(unique(subData[[i]][,indexClass])) > 1){
        subData[[i]] <- computeTree(child, subData[[i]], indexClass)
      } else if(length(unique(subData[[i]][,indexClass])) > 0){
        #print(length(unique(subData[[i]][,indexClass])))
        child$AddChild(unique(subData[[i]][,indexClass]))
      }
    }
  }
  return(tree)
}
```

```{r}
walkTree <- function(tree, testData){
  if(isLeaf(tree)){
    return(tree$name)
    }
    else{
  attribute <- grep(paste("\\b",tree$name,"\\b",sep=""), colnames(testData))
  #print(attribute)
  if(is.numeric(testData[[attribute]])){
    attAvg <- substring(tree$children[[1]]$name, 4)
    if(testData[[attribute]] > as.numeric(attAvg)){
      walkTree(tree$children[[2]]$children[[1]], testData)
    } else {
      walkTree(tree$children[[1]]$children[[1]], testData)
    }
  } 
  else {
    for(i in 1:tree$count){
      if(identical(testData[[attribute]],tree$children[[i]]$name)){
        return(walkTree(tree$children[[i]]$children[[1]], testData))
      }
    }
  }
    }

}
```

```{r}
bootstraping <- function(data, indexClass){
  bsId <- sample(1:nrow(data), nrow(data), replace=TRUE)
  trainData <- data[bsId,]
  
  tree <- Node$new("ROOT")
  tree <- computeTree(tree, trainData, indexClass)
  
  return(tree)
}
```

```{r}
ensemble <- function(data, indexClass, nTrees){
  randomTrees <- list()
  for(i in 1:nTrees){
    randomTrees[[i]] <- bootstraping(data, indexClass)
  }
  return(randomTrees)
}
```

```{r}
voter <- function(ensembleL, testData){
  result <- vector()
  for(i in 1:length(ensembleL)){
    #("tree")
    #print(i)
    #print(ensembleL[[i]])
    if(length(walkTree(ensembleL[[i]], testData)) != 0){
      result[i] <- walkTree(ensembleL[[i]], testData)
    } 
  }
  #return(sort(result, decreasing=TRUE)[1])
  #print(result)
  return(names(which.max(table(result))))
}

```

```{r}
computeAcc <- function(ensembleL, testData, classIndex){
  dim <- length(unique(testData[,classIndex]))
  results <- matrix(0, nrow=dim, ncol = dim)
  precision <- vector()
  recall <- vector()
  fm <- vector()
  
  for(i in 1:nrow(testData)){
    #print(testData[i, classIndex])
    #print(voter(ensembleL, testData[i,]))
    result <- voter(ensembleL, testData[i,])
    if(testData[i,classIndex] == result){
      #print("test1")
      cell <- grep(testData[i,classIndex], unique(testData[,classIndex]))
      results[cell,cell] <- results[cell,cell]+1
    } else {
      row <- grep(result, unique(testData[,classIndex]))
      col <- grep(testData[i, classIndex], unique(testData[,classIndex]))
      
      results[row,col] = results[row,col]+1
    }
  }
  
  print(results)
  for(i in 1:dim) {
      recall[i] <- results[i,i]/sum(results[,i])
      precision[i] <- results[i,i]/sum(results[i,])
      fm[i] <- 2*(precision[i]*recall[i])/(precision[i]+recall[i])
  }
  return(fm)
}
```

```{r}
library(parallel)
library(iterators)
library(foreach)
library(doParallel)

sclass <- list()
idClass <- list()
randomClass <- list()
ListClass <-list()
folds <- list()

cores <- detectCores()
cl <- makeCluster(cores[1])
registerDoParallel(cl)
```

```{r}
ionoResults10  <- vector()
ionoResults25  <- vector()
ionoResults50  <- vector()
ionoResults100 <- vector()
ionoResults125 <- vector()
ionoResults150 <- vector()

data <- read.csv("ionosphere.csv",header = TRUE,stringsAsFactors = FALSE,sep=",")
#data <- data[,c(2,3,4,5,6,7,8,9,10,11,12,13,14,1)]
indexClass <- 35
classes <- unique(data[,indexClass])

for(j in 1:10){

for(i in 1:length(classes)){
  sclass[[i]] <- data[which(data[,indexClass] == classes[i]),]
  idClass[[i]] <- rep(1:10, (nrow(sclass[[i]])/10) + ceiling((nrow(sclass[[i]])%%10)/10))
  if(length(head(idClass[[i]], nrow(sclass[[i]])-length(idClass[[i]]))) > 0 ){
    idClass[[i]] <- head(idClass[[i]], nrow(sclass[[i]])-length(idClass[[i]]))}
    randomClass[[i]] <- sclass[[i]][sample(seq_along(sclass[[i]]), length(sclass[[i]]))]
    ListClass[[i]] <- split(sclass[[i]], idClass[[i]])
}

for(i in 1:10){
  folds[[i]] <- vector()
  for(k in 1:length(classes)){
    folds[[i]] <- rbind(folds[[i]], ListClass[[k]][i])
  }
  folds[[i]] <- do.call(rbind, folds[[i]])
}



results10 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 10
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results25 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 25
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results50 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 50
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results100 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 100
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results125 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 125
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results150 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 150
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

ionoResults10  <- c( ionoResults10,  results10)
ionoResults25  <- c( ionoResults25,  results25)
ionoResults50  <- c( ionoResults50,  results50)
ionoResults100 <- c(ionoResults100, results100)
ionoResults125 <- c(ionoResults125, results125)
ionoResults150 <- c(ionoResults150, results150)

}
```

```{r}

wineResults10  <- vector()
wineResults25  <- vector()
wineResults50  <- vector()
wineResults100 <- vector()
wineResults125 <- vector()
wineResults150 <- vector()

data <- read.csv("wine.csv",header = TRUE,stringsAsFactors = FALSE,sep=",")
data <- data[,c(2,3,4,5,6,7,8,9,10,11,12,13,14,1)]
indexClass <- 14
classes <- unique(data[,indexClass])

for(j in 1:10){

for(i in 1:length(classes)){
  sclass[[i]] <- data[which(data[,indexClass] == classes[i]),]
  idClass[[i]] <- rep(1:10, (nrow(sclass[[i]])/10) + ceiling((nrow(sclass[[i]])%%10)/10))
  if(length(head(idClass[[i]], nrow(sclass[[i]])-length(idClass[[i]]))) > 0 ){
    idClass[[i]] <- head(idClass[[i]], nrow(sclass[[i]])-length(idClass[[i]]))}
    randomClass[[i]] <- sclass[[i]][sample(seq_along(sclass[[i]]), length(sclass[[i]]))]
    ListClass[[i]] <- split(sclass[[i]], idClass[[i]])
}

for(i in 1:10){
  folds[[i]] <- vector()
  for(k in 1:length(classes)){
    folds[[i]] <- rbind(folds[[i]], ListClass[[k]][i])
  }
  folds[[i]] <- do.call(rbind, folds[[i]])
}



results10 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 10
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results25 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 25
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results50 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 50
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results100 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 100
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results125 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 125
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

results150 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 150
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
}

wineResults10  <- c( wineResults10,  results10)
wineResults25  <- c( wineResults25,  results25)
wineResults50  <- c( wineResults50,  results50)
wineResults100 <- c(wineResults100, results100)
wineResults125 <- c(wineResults125, results125)
wineResults150 <- c(wineResults150, results150)

}
```

```{r}

pimaResults10  <- vector()
pimaResults25  <- vector()
pimaResults50  <- vector()
pimaResults100 <- vector()
pimaResults125 <- vector()
pimaResults150 <- vector()

data <- read.csv("pima.csv",header = TRUE,stringsAsFactors = FALSE,sep="\t")
#data <- data[,c(2,3,4,5,6,7,8,9,10,11,12,13,14,1)]
indexClass <- 9
classes <- unique(data[,indexClass])

for(j in 1:10){

for(i in 1:length(classes)){
  sclass[[i]] <- data[which(data[,indexClass] == classes[i]),]
  idClass[[i]] <- rep(1:10, (nrow(sclass[[i]])/10) + ceiling((nrow(sclass[[i]])%%10)/10))
  if(length(head(idClass[[i]], nrow(sclass[[i]])-length(idClass[[i]]))) > 0 ){
    idClass[[i]] <- head(idClass[[i]], nrow(sclass[[i]])-length(idClass[[i]]))}
    randomClass[[i]] <- sclass[[i]][sample(seq_along(sclass[[i]]), length(sclass[[i]]))]
    ListClass[[i]] <- split(sclass[[i]], idClass[[i]])
}

for(i in 1:10){
  folds[[i]] <- vector()
  for(k in 1:length(classes)){
    folds[[i]] <- rbind(folds[[i]], ListClass[[k]][i])
  }
  folds[[i]] <- do.call(rbind, folds[[i]])
}

results10 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 10
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
  gc()  
}



results25 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 25
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
  gc()
}



results50 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 50
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
  gc()
}

results100 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 100
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
  gc()
}

results125 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 125
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
  gc()
}

results150 <- foreach(i=1:10, .combine=cbind, .packages = 'data.tree') %dopar% {
  test <- folds[[i]]
  train <- do.call(rbind.data.frame, folds[-i])
  
  nTrees <- 150
  randomTrees <- ensemble(train, indexClass, nTrees)
  tempResults <- computeAcc(randomTrees, test, indexClass)
  tempResults
  gc()
}

pimaResults10  <- c( pimaResults10,  results10)
pimaResults25  <- c( pimaResults25,  results25)
pimaResults50  <- c( pimaResults50,  results50)
pimaResults100 <- c(pimaResults100, results100)
pimaResults125 <- c(pimaResults125, results125)
pimaResults150 <- c(pimaResults150, results150)

gc()
}

stopCluster(cl)

```